    name: GitHub Classroom Workflow

    on: 
      push:
        branches:
        - '*'
        - '!badges'

    jobs:
      changedfiles:
        runs-on: ubuntu-latest
        outputs:
          grading: ${{ steps.changes.outputs.grading}}
          proceed: ${{ steps.proceed.outputs.permission}}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Get changed files
            id: changes
            run: |
              echo "::set-output name=grading::$(git diff `git rev-list HEAD | tail -n 1` HEAD --name-only -- __tests__/tasks.*.js | xargs)"
          - name: check permission to proceed
            id: proceed
            run: |
              echo "::set-output name=permission::${{ github.repository_owner == 'DigitalCareerInstitute' || steps.changes.outputs.grading == '' }}"
          - name: message
            if: ${{ steps.changes.outputs.grading != '' }}
            run: echo "Grading files CHANGED ${{steps.changes.outputs.grading}}"
          - name: check result
            if: ${{ steps.proceed.outputs.permission != 'true' }}
            run: exit 1

      build:
        name: Autograding
        runs-on: ubuntu-latest
        needs: changedfiles
        if: ${{ needs.changedfiles.outputs.proceed }}
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

          # add id to action so outputs can be used
          - uses: education/autograding@v1
            id: autograder
            continue-on-error: true

          # make dir for badges
          - name: badges branch and make dir
            run: |
              git checkout --orphan badges
              git rm -rf .
              mkdir -p .github/badges

          # make points badge
          - name: points badge
            uses: emibcn/badge-action@v1
            with:
              LABEL: 'Points'
              STATUS: ${{ steps.autograder.outputs.points }}
              LABEL-COLOR: 2f496e
              COLOR: 2988bc
              SCALE: 2
              STYLE: flat
              path: '.github/badges/points.svg'

          - name: Upload badge as artifact
            uses: actions/upload-artifact@v2
            with:
              name: badge
              path: '.github/badges/points.svg'
              if-no-files-found: error
              retention-days: 1

          # commit and push badge if score has changed
          - name: Commit badge
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add '.github/badges/points.svg'
              git commit -m "Add/Update badge"
            continue-on-error: true
          - name: Push badge commit
            uses: ad-m/github-push-action@master
            if: success()
            with:
              force: true
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: badges

          # fail job if autograder returns failed
          # outcome can be 'success', 'failure', 'cancelled', or 'skipped'
          # trigger fail either on !success or on failure depending on preference
          - name: check autograder pass fail
            if: ${{ steps.autograder.outcome != 'success' }}
            # if: ${{ steps.autograder.outcome == 'failure' }}
            # if: ${{ failure }}
            run: exit 1
